### PR TITLE
Fix test broken due to recent MOOSE change 

### LINKED ISSUE #17: Fix test due to changes in return mapping models in MOOSE
A recent MOOSE commit (PR #8914) broke the THM_injection test.

### PR DESCRIPTION
**Pull request by bwspenc**
closes #17

### CODE REVIEW

**Comment by bwspenc** [comment]
@permcody or @yidongxiainl -- could one of you activate the tests please?  I don't think I have permission to activate the tests.

**Comment by yidongxiainl** [comment]
@bwspenc I do not see any option on the page to activate the tests. Would you let me know how to do that?

**Comment by bwspenc** [comment]
@WilkAndy I made a quick attempt to fix this test by moving over to the new Update model, but the test is diffing.  It's complaining that there's an unused parameter: `initial_stress` in this model, which was used before in the old model.  I imagine that's why it's diffing.  It looks like `TwoParameterPlasticityStressUpdate` checks for `initial_stress`, but that parameter isn't actually registered.  Thoughts?

**Comment by WilkAndy** [comment]
Oh, that's a bug in TwoParameterPlasticityStressUpdate.  Thanks for seeing it!   In the input file, the initial_stress should be removed from all classes that derive from it (CappedWeakInclinedPlaneStressUpdate in this case) and shoved into ComputeMultipleInelasticStress instead.

**Comment by bwspenc** [comment]
OK, I'll give that a try.

**Comment by bwspenc** [comment]
@WilkAndy Thanks for pointing me in the right direction!  @yidongxiainl It finally passed the tests, so I think it's good to go.

**Comment by WilkAndy** [comment]
phew!   Thanks for doing this, @bwspenc

**Pull request merged**
