### PR TITLE
Test live serve with some minor edits

### PR DESCRIPTION
**Pull request by crswong888**
@rpodgorney PLEASE DO NOT MERGE THIS. The commit is pending merge idaholab/moose#18010. 

Also, @loganharbour is testing that this PR triggers the civet recipe for building Falcon documentation (even though it will be slightly broken because of gc and large_media fails).

(refs #45)

### CODE REVIEW

**Comment by rpodgorney** [comment]
@crswong888 @loganharbour thanks guys.  

Any action for me at all?

**Comment by crswong888** [comment]
@rpodgorney I don't think so!

**Comment by crswong888** [comment]
@rpodgorney we're just waiting on the submodule update with the geochemistry fix then we can merge this and let civet do the rest!

**Comment by rpodgorney** [comment]
@crswong888 I am guessing this is automated....any ETA?

**Comment by loganharbour** [comment]
I'd say 2 hours to get moose to update the fixes in falcon, and then another hour to get this in + into devel and master to publish.

**Pull request merged**
