### PR TITLE
remove variableGradientAux

### LINKED ISSUE #117: remove variableGradientAux
VariableGradientAux does the same thing as the framework object VariableGradientComponent.  So delete VariableGradientAux and replace any tests or uses of it with VariableGradientComponent.

### PR DESCRIPTION
**Pull request by lynnmunday**
closes #117

### CODE REVIEW

**Comment by lynnmunday** [comment]
@loganharbour Do you know whats going on here.  I deleted untested objects and now the coverage is failing. If anything, it should have gotten better.

**Comment by loganharbour** [comment]
Invalidation magic

**Comment by lynnmunday** [comment]
Will you merge this too?

**Comment by lynnmunday** [comment]
@rpodgorney or @loganharbour will you review and merge

**Pull request merged**
