### PR TITLE
Moving over former kestrel capabilities to falcon

### LINKED ISSUE #95: transfer for kestrel app functionality to falcon
Before THM was open sourced, a test application (kestrel) was built to try multi apps between falcon and THM.  Now that THM is OSS, we need to add the capabilities built in kestrel into falcon

### PR DESCRIPTION
**Pull request by rpodgorney**
closes #95

### CODE REVIEW

**Comment by rpodgorney** [comment]
Note--I see an error on lines 33 and 35 in the MAKEFILE, I think all the tests will still pass tho--but the lines need too be fixed before they are merged

**Comment by rpodgorney** [comment]
@cticenhour -- do you know anything about the doco system---it's causing my PR to die in testing

**Comment by cticenhour** [comment]
At first glance it looks like you might be missing some things in your `Content` section within `doc/config.yaml`. You have added modules to your Makefile but not made the appropriate changes to your documentation configuration.

**Comment by cticenhour** [comment]
You'll also want to add the appropriate entries to the `Extensions/MooseDocs.extensions.appsyntax` and `Extensions/MooseDocs.extensions.sqa` sections.

**Comment by rpodgorney** [comment]
Thanks

Robert Podgorney, Ph.D.
Chief Computational Scientist   |   Advanced Scientific Computing Division
Fellow  |   Nuclear Science and Technology Directorate
***@***.******@***.***>   |   208-526-1524
Idaho National Laboratory   |   1955 Fremont Ave.   |   Idaho Falls, ID   |   83415
_______________________________

[signature_1038174214]

Statement of Confidentiality
The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.



From: Casey Icenhour ***@***.***>
Reply-To: idaholab/falcon ***@***.***>
Date: Wednesday, June 29, 2022 at 2:57 PM
To: idaholab/falcon ***@***.***>
Cc: "Robert K. Podgorney" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [idaholab/falcon] Moving over former kestrel capabilities to falcon (PR #96)


You'll also want to add the appropriate entries to the Extensions/MooseDocs.extensions.appsyntax and Extensions/MooseDocs.extensions.sqa sections.

**Comment by cticenhour** [comment]
One day, one day.... 🤣

**Comment by rpodgorney** [comment]
Thanks @cticenhour @loganharbour

**Pull request merged**
