### PR TITLE
Fixed stress

### PR DESCRIPTION
**Pull request by AhmedAlmetwally**
It addresses issue #58

### CODE REVIEW

**Comment by AhmedAlmetwally** [comment]
@rpodgorney @crswong888 please activate the testing for these commits.
This commits changes the Makefile to include the Richards' module.
The input for Mandel problem needs the "poroFullSatMaterial" object which in is the Richard module.

**Review by rpodgorney — APPROVED** [review]
Looks good via a quick glance.  This PR adds an example case for a "fixed stress" multiapp -- a way to solve TH separately from M in the coupled Thermo-Hysrailic-Mechanical simulation

**Comment by rpodgorney** [comment]
@loganharbour I'm a little stuck in this PR--how exactly do we activate it so that the "Test" will run?

**Comment by rpodgorney** [comment]
Check your commits—your tests are failing…..



test:testProblem.steady_run: Working Directory: /opt/civet/build_2/falcon/test/tests/testProblem
test:testProblem.steady_run: Running command: /opt/civet/build_2/falcon/falcon-opt -i thm_steady.i --timing Outputs/perf_graph=true --no-gdb-backtrace
test:testProblem.steady_run:
test:testProblem.steady_run:
test:testProblem.steady_run:
test:testProblem.steady_run: *** ERROR ***
test:testProblem.steady_run: Unable to open file "/opt/civet/build_2/falcon/test/tests/testProblem/mesh_vcoarse.e". Check to make sure that it exists and that you have read permission.
test:testProblem.steady_run:
test:testProblem.steady_run: Stack frames: 15
test:testProblem.steady_run: 0: libMesh::print_trace(std::ostream&)
test:testProblem.steady_run: 1: moose::internal::mooseErrorRaw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
test:testProblem.steady_run: 2: void mooseError<char const*>(char const*&&)
test:testProblem.steady_run: 3: MooseUtils::checkFileReadable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool)
test:testProblem.steady_run: 4: FileMesh::buildMesh()
test:testProblem.steady_run: 5: MooseMesh::init()
test:testProblem.steady_run: 6: SetupMeshAction::act()
test:testProblem.steady_run: 7: Action::timedAct()
test:testProblem.steady_run: 8: ActionWarehouse::executeActionsWithAction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
test:testProblem.steady_run: 9: ActionWarehouse::executeAllActions()
test:testProblem.steady_run: 10: MooseApp::runInputFile()
test:testProblem.steady_run: 11: MooseApp::run()
test:testProblem.steady_run: 12: /opt/civet/build_2/falcon/falcon-opt() [0x403cce]
test:testProblem.steady_run: 13: __libc_start_main
test:testProblem.steady_run: 14: /opt/civet/build_2/falcon/falcon-opt() [0x403f0e]
test:testProblem.steady_run: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
test:testProblem.steady_run: [unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
test:testProblem.steady_run: :
test:testProblem.steady_run: system msg for write_line failure : Bad file descriptor
test:testProblem.steady_run:
test:testProblem.steady_run:
test:testProblem.steady_run:
test:testProblem.steady_run: *** ERROR ***
test:testProblem.steady_run: Unable to open file "/opt/civet/build_2/falcon/test/tests/testProblem/mesh_vcoarse.e". Check to make sure that it exists and that you have read permission.
test:testProblem.steady_run:
test:testProblem.steady_run: Stack frames: 15
test:testProblem.steady_run: 0: libMesh::print_trace(std::ostream&)
test:testProblem.steady_run: 1: moose::internal::mooseErrorRaw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
test:testProblem.steady_run: 2: void mooseError<char const*>(char const*&&)
test:testProblem.steady_run: 3: MooseUtils::checkFileReadable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool)
test:testProblem.steady_run: 4: FileMesh::buildMesh()
test:testProblem.steady_run: 5: MooseMesh::init()
test:testProblem.steady_run: 6: SetupMeshAction::act()
test:testProblem.steady_run: 7: Action::timedAct()
test:testProblem.steady_run: 8: ActionWarehouse::executeActionsWithAction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
test:testProblem.steady_run: 9: ActionWarehouse::executeAllActions()
test:testProblem.steady_run: 10: MooseApp::runInputFile()
test:testProblem.steady_run: 11: MooseApp::run()
test:testProblem.steady_run: 12: /opt/civet/build_2/falcon/falcon-opt() [0x403cce]
test:testProblem.steady_run: 13: __libc_start_main
test:testProblem.steady_run: 14: /opt/civet/build_2/falcon/falcon-opt() [0x403f0e]
test:testProblem.steady_run: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
test:testProblem.steady_run: [unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
test:testProblem.steady_run: :
test:testProblem.steady_run: system msg for write_line failure : Bad file descriptor
test:testProblem.steady_run:
test:testProblem.steady_run:
test:testProblem.steady_run: Exit Code: 1
test:testProblem.steady_run: ################################################################################
test:testProblem.steady_run: Tester failed, reason: ERRMSG
test:testProblem.steady_run:
[0.224s]     FAIL test:testProblem.steady_run FAILED (ERRMSG)
[0.656s]       OK test:PT_TH_faust.PT_TH_faust
[0.439s]       OK test:PT_H_injection.PT_H_injection
test:testProblem.transient_run: Working Directory: /opt/civet/build_2/falcon/test/tests/testProblem
test:testProblem.transient_run: Running command: /opt/civet/build_2/falcon/falcon-opt -i thm_transient.i --timing Outputs/perf_graph=true --no-gdb-backtrace
test:testProblem.transient_run:
test:testProblem.transient_run: Error opening ExodusII mesh file: /opt/civet/build_2/falcon/test/tests/testProblem/thm_transient_ic.e
test:testProblem.transient_run: Stack frames: 15
test:testProblem.transient_run: 0: libMesh::print_trace(std::ostream&)
test:testProblem.transient_run: 1: libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*)
test:testProblem.transient_run: 2: libMesh::ExodusII_IO_Helper::open(char const*, bool)
test:testProblem.transient_run: 3: libMesh::ExodusII_IO::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
test:testProblem.transient_run: 4: FileMeshGenerator::generate()
test:testProblem.transient_run: 5: MeshGenerator::generateInternal()
test:testProblem.transient_run: 6: MooseApp::executeMeshGenerators()
test:testProblem.transient_run: 7: Action::timedAct()
test:testProblem.transient_run: 8: ActionWarehouse::executeActionsWithAction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
test:testProblem.transient_run: 9: ActionWarehouse::executeAllActions()
test:testProblem.transient_run: 10: MooseApp::runInputFile()
test:testProblem.transient_run: 11: MooseApp::run()
test:testProblem.transient_run: 12: /opt/civet/build_2/falcon/falcon-opt() [0x403cce]
test:testProblem.transient_run: 13: __libc_start_main
test:testProblem.transient_run: 14: /opt/civet/build_2/falcon/falcon-opt() [0x403f0e]
test:testProblem.transient_run: [0] /opt/civet/build_2/falcon/moose/scripts/../libmesh/src/mesh/exodusII_io_helper.C, line 523, compiled Jul 23 2021 at 10:06:51
test:testProblem.transient_run:
test:testProblem.transient_run:
test:testProblem.transient_run: *** ERROR ***
test:testProblem.transient_run: Error opening ExodusII mesh file: /opt/civet/build_2/falcon/test/tests/testProblem/thm_transient_ic.e
test:testProblem.transient_run:
test:testProblem.transient_run: Stack frames: 7
test:testProblem.transient_run: 0: libMesh::print_trace(std::ostream&)
test:testProblem.transient_run: 1: moose::internal::mooseErrorRaw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
test:testProblem.transient_run: 2: void mooseError<char const*>(char const*&&)
test:testProblem.transient_run: 3: /opt/civet/build_2/falcon/moose/framework/libmoose-opt.so.0(+0x89872b) [0x7fb39e61a72b]
test:testProblem.transient_run: 4: /opt/civet/build_2/falcon/falcon-opt() [0x403cce]
test:testProblem.transient_run: 5: __libc_start_main
test:testProblem.transient_run: 6: /opt/civet/build_2/falcon/falcon-opt() [0x403f0e]
test:testProblem.transient_run: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
test:testProblem.transient_run: [unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
test:testProblem.transient_run: :
test:testProblem.transient_run: system msg for write_line failure : Bad file descriptor
test:testProblem.transient_run:
test:testProblem.transient_run: Error opening ExodusII mesh file: /opt/civet/build_2/falcon/test/tests/testProblem/thm_transient_ic.e
test:testProblem.transient_run: Stack frames: 15
test:testProblem.transient_run: 0: libMesh::print_trace(std::ostream&)
test:testProblem.transient_run: 1: libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*)
test:testProblem.transient_run: 2: libMesh::ExodusII_IO_Helper::open(char const*, bool)
test:testProblem.transient_run: 3: libMesh::ExodusII_IO::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
test:testProblem.transient_run: 4: FileMeshGenerator::generate()
test:testProblem.transient_run: 5: MeshGenerator::generateInternal()
test:testProblem.transient_run: 6: MooseApp::executeMeshGenerators()
test:testProblem.transient_run: 7: Action::timedAct()
test:testProblem.transient_run: 8: ActionWarehouse::executeActionsWithAction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
test:testProblem.transient_run: 9: ActionWarehouse::executeAllActions()
test:testProblem.transient_run: 10: MooseApp::runInputFile()
test:testProblem.transient_run: 11: MooseApp::run()
test:testProblem.transient_run: 12: /opt/civet/build_2/falcon/falcon-opt() [0x403cce]
test:testProblem.transient_run: 13: __libc_start_main
test:testProblem.transient_run: 14: /opt/civet/build_2/falcon/falcon-opt() [0x403f0e]
test:testProblem.transient_run: [0] /opt/civet/build_2/falcon/moose/scripts/../libmesh/src/mesh/exodusII_io_helper.C, line 523, compiled Jul 23 2021 at 10:06:51
test:testProblem.transient_run:
test:testProblem.transient_run:
test:testProblem.transient_run: *** ERROR ***
test:testProblem.transient_run: Error opening ExodusII mesh file: /opt/civet/build_2/falcon/test/tests/testProblem/thm_transient_ic.e
test:testProblem.transient_run:
test:testProblem.transient_run: Stack frames: 7
test:testProblem.transient_run: 0: libMesh::print_trace(std::ostream&)
test:testProblem.transient_run: 1: moose::internal::mooseErrorRaw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
test:testProblem.transient_run: 2: void mooseError<char const*>(char const*&&)
test:testProblem.transient_run: 3: /opt/civet/build_2/falcon/moose/framework/libmoose-opt.so.0(+0x89872b) [0x7fb39e61a72b]
test:testProblem.transient_run: 4: /opt/civet/build_2/falcon/falcon-opt() [0x403cce]
test:testProblem.transient_run: 5: __libc_start_main
test:testProblem.transient_run: 6: /opt/civet/build_2/falcon/falcon-opt() [0x403f0e]
test:testProblem.transient_run: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
test:testProblem.transient_run: [unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
test:testProblem.transient_run: :
test:testProblem.transient_run: system msg for write_line failure : Bad file descriptor
test:testProblem.transient_run:
test:testProblem.transient_run:
test:testProblem.transient_run: Exit Code: 1
test:testProblem.transient_run: ################################################################################
test:testProblem.transient_run: Tester failed, reason: ERRMSG
test:testProblem.transient_run:
[0.217s]     FAIL test:testProblem.transient_run FAILED (ERRMSG)
test:testProblem.steady_run3: Working Directory: /opt/civet/build_2/falcon/test/tests/testProblem
test:testProblem.steady_run3: Running command: /opt/civet/build_2/falcon/falcon-opt -i thm_steady.i --timing Outputs/perf_graph=true --no-gdb-backtrace
test:testProblem.steady_run3:
test:testProblem.steady_run3:
test:testProblem.steady_run3:
test:testProblem.steady_run3: *** ERROR ***
test:testProblem.steady_run3: Unable to open file "/opt/civet/build_2/falcon/test/tests/testProblem/mesh_vcoarse.e". Check to make sure that it exists and that you have read permission.
test:testProblem.steady_run3:
test:testProblem.steady_run3: Stack frames: 15
test:testProblem.steady_run3: 0: libMesh::print_trace(std::ostream&)
test:testProblem.steady_run3: 1: moose::internal::mooseErrorRaw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
test:testProblem.steady_run3: 2: void mooseError<char const*>(char const*&&)
test:testProblem.steady_run3: 3: MooseUtils::checkFileReadable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool)
test:testProblem.steady_run3: 4: FileMesh::buildMesh()
test:testProblem.steady_run3: 5: MooseMesh::init()
test:testProblem.steady_run3: 6: SetupMeshAction::act()
test:testProblem.steady_run3: 7: Action::timedAct()
test:testProblem.steady_run3: 8: ActionWarehouse::executeActionsWithAction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
test:testProblem.steady_run3: 9: ActionWarehouse::executeAllActions()
test:testProblem.steady_run3: 10: MooseApp::runInputFile()
test:testProblem.steady_run3: 11: MooseApp::run()
test:testProblem.steady_run3: 12: /opt/civet/build_2/falcon/falcon-opt() [0x403cce]
test:testProblem.steady_run3: 13: __libc_start_main
test:testProblem.steady_run3: 14: /opt/civet/build_2/falcon/falcon-opt() [0x403f0e]
test:testProblem.steady_run3: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
test:testProblem.steady_run3: [unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
test:testProblem.steady_run3: :
test:testProblem.steady_run3: system msg for write_line failure : Bad file descriptor
test:testProblem.steady_run3:
test:testProblem.steady_run3:
test:testProblem.steady_run3:
test:testProblem.steady_run3: *** ERROR ***
test:testProblem.steady_run3: Unable to open file "/opt/civet/build_2/falcon/test/tests/testProblem/mesh_vcoarse.e". Check to make sure that it exists and that you have read permission.
test:testProblem.steady_run3:
test:testProblem.steady_run3: Stack frames: 15
test:testProblem.steady_run3: 0: libMesh::print_trace(std::ostream&)
test:testProblem.steady_run3: 1: moose::internal::mooseErrorRaw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
test:testProblem.steady_run3: 2: void mooseError<char const*>(char const*&&)
test:testProblem.steady_run3: 3: MooseUtils::checkFileReadable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool)
test:testProblem.steady_run3: 4: FileMesh::buildMesh()
test:testProblem.steady_run3: 5: MooseMesh::init()
test:testProblem.steady_run3: 6: SetupMeshAction::act()
test:testProblem.steady_run3: 7: Action::timedAct()
test:testProblem.steady_run3: 8: ActionWarehouse::executeActionsWithAction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
test:testProblem.steady_run3: 9: ActionWarehouse::executeAllActions()
test:testProblem.steady_run3: 10: MooseApp::runInputFile()
test:testProblem.steady_run3: 11: MooseApp::run()
test:testProblem.steady_run3: 12: /opt/civet/build_2/falcon/falcon-opt() [0x403cce]
test:testProblem.steady_run3: 13: __libc_start_main
test:testProblem.steady_run3: 14: /opt/civet/build_2/falcon/falcon-opt() [0x403f0e]
test:testProblem.steady_run3: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
test:testProblem.steady_run3: [unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
test:testProblem.steady_run3: :
test:testProblem.steady_run3: system msg for write_line failure : Bad file descriptor
test:testProblem.steady_run3:
test:testProblem.steady_run3:
test:testProblem.steady_run3: Exit Code: 1
test:testProblem.steady_run3: ################################################################################
test:testProblem.steady_run3: Tester failed, reason: ERRMSG
test:testProblem.steady_run3:
[0.210s]     FAIL test:testProblem.steady_run3 FAILED (ERRMSG)



--
Robert K. Podgorney, PhD
Chief Computational Scientist
Advanced Scientific Computing Division
Idaho National Laboratory

Office: 208-526-1524<tel:208-526-1524>
Cell: 208-520-9361<tel:208-520-9361>
email: ***@***.******@***.***>
Statement of Confidentiality
The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.


From: AhmedAlmetwally ***@***.***>
Reply-To: idaholab/falcon ***@***.***>
Date: Thursday, July 22, 2021 at 6:24 PM
To: idaholab/falcon ***@***.***>
Cc: Robert Podgorney ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [idaholab/falcon] Fixed stress (#59)


@rpodgorney<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frpodgorney&data=04%7C01%7Crobert.podgorney%40inl.gov%7C2b9e38dd41fa414f8fd808d94d7040e5%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637625966789620734%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RgRYQRNfAraxP3uySjQO5PuNBg6mGxrPXrWURdtNcXQ%3D&reserved=0> @crswong888<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcrswong888&data=04%7C01%7Crobert.podgorney%40inl.gov%7C2b9e38dd41fa414f8fd808d94d7040e5%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637625966789630688%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gV%2BFQp51rBVpoSfH0VyVwyTAv6RnLURRN9%2Fvza%2BwYeE%3D&reserved=0> please activate the testing for these commits.
This commits changes the Makefile to include the Richards' module.
The input for Mandel problem needs the "poroFullSatMaterial" object which in is the Richard module.

**Comment by lynnmunday** [comment]
@AhmedAlmetwally  Logan merged my pr that reverts the failing test so you can update your branch and push again.  You can call me if you need help with it.

**Comment by AhmedAlmetwally** [comment]
@loganharbour Would you rerun the documentation test, It should pass because I did not change the documentation of Falcon.

**Comment by lynnmunday** [comment]
@rpodgorney Would you review this again?  We got everything to pass.  We added the Richards module which was used in mandel.i.  Adding this module required us to change the config.yml to ignore the richards ignores.  I've never had to do that before in other apps with other modules.  I couldn't find another app that used the Richards module so I so I didn't have anything to copy and paste.

**Comment by crswong888** [comment]
@lynnmunday this is the correct syntax for adding the richards module docs.

**Comment by rpodgorney** [comment]
I DO NOT need to review again.  Thanks everyone


--
Robert K. Podgorney
Chief Computational Scientist
Advanced Scientific Computing Division
Idaho National Laboratory

Office: 208-526-1524<tel:208-526-1524>
Cell: 208-520-9361<tel:208-520-9361>
email: ***@***.******@***.***>
Statement of Confidentiality
The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.


From: Lynn Munday ***@***.***>
Date: Tuesday, August 3, 2021 at 2:27 PM
To: idaholab/falcon ***@***.***>
Cc: Robert K. Podgorney ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [idaholab/falcon] Fixed stress (#59)

@rpodgorney<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frpodgorney&data=04%7C01%7Crobert.podgorney%40inl.gov%7Ca49825bb2bd34a20092508d956bd259e%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637636192648858031%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MUgj8ZxNgDNwapFM2f0Lgn%2Bqfi0EhIbfBK%2BkT09uVVc%3D&reserved=0> Would you review this again? We got everything to pass. We added the Richards module which was used in mandel.i. Adding this module required us to change the config.yml to ignore the richards ignores. I've never had to do that before in other apps with other modules. I couldn't find another app that used the Richards module so I so I didn't have anything to copy and paste.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fidaholab%2Ffalcon%2Fpull%2F59%23issuecomment-892142985&data=04%7C01%7Crobert.podgorney%40inl.gov%7Ca49825bb2bd34a20092508d956bd259e%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637636192648858031%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MT8tGoRijRlVhXzwr8THm7lP6L8cg%2FfDgG1rPeAj9pM%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACWGDT5BEUMYBAJ3QAY4KSTT3BGL5ANCNFSM5A3AS74Q&data=04%7C01%7Crobert.podgorney%40inl.gov%7Ca49825bb2bd34a20092508d956bd259e%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637636192648867986%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uzI%2F8c%2BHiH%2BnPi9OrUtceSZYcSirnEEl8A%2B1h4sfMQo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crobert.podgorney%40inl.gov%7Ca49825bb2bd34a20092508d956bd259e%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637636192648877941%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=S8LfpG6gar8iAOnXfRuO0U5kVznp7615asGKb%2Bp7WTg%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Crobert.podgorney%40inl.gov%7Ca49825bb2bd34a20092508d956bd259e%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637636192648877941%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E4ZeYKiMrgqsSqonlWQksk%2Bru061p6aGdIaWrSS8NT4%3D&reserved=0>.

**Comment by lynnmunday** [comment]
@AhmedAlmetwally the porousFlow module has changed and the syntax in you sub app is no longer valid.  I'll take a look at it.

**Comment by lynnmunday** [comment]
@loganharbour We fixed everything and it is no longer a draft and is ready to merge.   Can you change my falcon status so that I can push to peoples commits and merge code?  Thanks

**Comment by rpodgorney** [comment]
@Logan H. ***@***.***>, I am OK with elevating Lynn in Falcon


--
Robert K. Podgorney, PhD
Chief Computational Scientist
Advanced Scientific Computing Division
Idaho National Laboratory

Office: 208-526-1524<tel:208-526-1524>
email: ***@***.******@***.***>
Statement of Confidentiality
The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.


From: Lynn Munday ***@***.***>
Date: Monday, August 9, 2021 at 3:48 PM
To: idaholab/falcon ***@***.***>
Cc: Robert K. Podgorney ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [idaholab/falcon] Fixed stress (#59)

@loganharbour<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Floganharbour&data=04%7C01%7Crobert.podgorney%40inl.gov%7Cdc2773326f4340686dc708d95b7f6759%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637641425020809233%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Q9DWNcO5oLxz2zYn6N4EWJc757%2BuRHtFpxLdURyCOag%3D&reserved=0> We fixed everything and it is no longer a draft and is ready to merge. Can you change my falcon status so that I can push to peoples commits and merge code? Thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fidaholab%2Ffalcon%2Fpull%2F59%23issuecomment-895573221&data=04%7C01%7Crobert.podgorney%40inl.gov%7Cdc2773326f4340686dc708d95b7f6759%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637641425020809233%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=V9umTw3ZpfZjWxMAMZSGwBG1IwouDpePdap4pKn2W%2BI%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACWGDTYSUDQ3OIIBC6FQDDLT4BEKHANCNFSM5A3AS74Q&data=04%7C01%7Crobert.podgorney%40inl.gov%7Cdc2773326f4340686dc708d95b7f6759%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637641425020819165%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4G11pAOqszwKZmaGxaa4ac30XmsmPKuzWWnstvIMzKs%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crobert.podgorney%40inl.gov%7Cdc2773326f4340686dc708d95b7f6759%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637641425020819165%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2Fj%2FJ9e5tL3kOnC%2F3a4ccnfJ12ROfTxNy2rAkh8jUba0%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Crobert.podgorney%40inl.gov%7Cdc2773326f4340686dc708d95b7f6759%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637641425020829130%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PCvXB3xiNHLMWFy6hT1%2Bs3rLiRiG%2Fb26egm5rhipx%2Fg%3D&reserved=0>.

**Pull request merged**
