### PR TITLE
add the FORGE project Yr 1 inversion case study doc

### PR DESCRIPTION
**Pull request by jonghyunharrylee**
Pull request for the Purdue_5-2557 project Year 1 case study document according to the project milestone 3.4.3. This example shows how to identify effective permeability and thermal conductivity parameters from sparse pressure, temperature, and displacement measurements.  The measurements were generated from the Utah Forge native state model. The document can be previewed from https://www2.hawaii.edu/~jonghyun/forge/examples/index.html

### CODE REVIEW

**Comment by rpodgorney** [comment]
@loganharbour I need help walking this through the review and approval process.

**Comment by rpodgorney** [comment]
@somu15 @lynnmunday can you review this PR?  It is a FORGE awardee who is adding some inversion processes.  I looked through it a bit and am wondering is dome of the inversion functionality built into the input file belongs in a script

**Comment by somu15** [comment]
@jonghyunharrylee The markdown page mostly looks good to me. I would prefer adding more details on the optimization algorithm that you are running through Python.

**Comment by somu15** [comment]
On a related note, we have been developing parallelizable Bayesian inverse UQ capabilities in MOOSE. The PR is up https://github.com/idaholab/moose/pull/23839 and we will merge this soon upon finalizing the documentation. I feel it'd make sense to perform inverse UQ given that practical geophysical data has noise in it and the computational model may not capture all the physics involved in the data. If you're interested in something like this, we can discuss more.

**Comment by lynnmunday** [comment]
@rpodgorney and @jonghyunharrylee is more going to be added to this commit like the input files and test?  The markdown should just reference the input file code blocks and not have the input file blocks pasted into it.  Maybe we can make part of it a fast running example just to make sure the input file syntax doesn't change.  We don't need to test the python script.  The python script also should not be included in the documentation.  Maybe you can check the python script in too, but not test it, and then point to the file from the documentation.  Since the python script is not being tested, it will likely get broken at some point and we will never know.  @loganharbour what is the Moose teams view on checking in Python scripts?

**Comment by rpodgorney** [comment]
thanks @lynnmunday.  I think you are correct, we need to structure the commit as you describe.  @jonghyunharrylee please make those recommended changes

**Comment by jonghyunharrylee** [comment]
Thank all for the suggestions:  

@somu15 I will add more about Gauss-Newton method used for the optimization. Currently no UQ is considered for a simple illustration while linearized uncertainty under Gaussian prior assumption can be computed. This preliminary result report is for a mandatory Year 1 FORGE project milestone and our team will post a final product for heterogeneous permeability field estimation with UQ next years. I plan to use our own inverse modeling code (https://github.com/jonghyunharrylee/pyPCGA) but am open to using INL's (inverse) UQ software. I am not sure how flexible the UQ software is to integrate domain-specific ML (i.e., deep generative model trained from fracture-upscaled permeability field samples in python) part that will describes complex fracture-based permeability fields in a smaller latent space though..

@lynnmunday: The python code implement a Gauss-Newton method for an optimization of input parameters in FALCON by reading the output of FALCON and then updating the effective, homogeneous permeability tensor in the input until convergence. It should work for any black-box solvers and as long as the input/output structures of FALCON stay the same. I can upload the python script elsewhere (my github repo?) and point to it in the documentation. I do not think the application described in the documentation can be readily checked within FALCON or make test because the parameter calibration requires numerous runs of FALCON. I am thinking of two modifications: 

1. remove the python script and add a link to the python script
2. add more description about the optimization used in this preliminary inversion example.

If you have any further suggestions, please let me know.

**Comment by lynnmunday** [comment]
@jonghyunharrylee You need to check in a MOOSE/Falcon input file and test file so that it can be tested to make sure the user syntax does not regress.  We have tests that only check that the syntax in an input file is still valid.  We usually make a smaller example of the bigger simulation that includes all of the relevant input blocks so that it can be run quickly.  You would then be able to reference all of these code blocks from your markdown.  I think @rpodgorney is fine with you adding the python file into the repository and I think you will also be able to reference that python file from your markdown.  You should try to avoid pasting in large chunks of a script or input file into the markdown.  

It would be straightforward to solve a simple optimization problem like this using the MOOSE optimization module.  Does part of your FORGE work involve development of new features in MOOSE or will you only be developing python that requires calling a blackbox FEM solver?  I don't know if the falcon repository is the right place for python scripts that execute MOOSE simulations and post process the results.  MOOSE has the basic capabilities you are needing either in the stochastic_tools module or the optimization module but these would need to be specialized for your particular algorithms.  It would be great if you all were able to develop some of your code in MOOSE and there is a large user base to help answer questions on development and running simulations.

**Comment by jonghyunharrylee** [comment]
@lynnmunday Thanks for the suggestions! The project milestone is specific to the Utah FORGE site application and I am not sure a simple model would be ok for the progress reporting/documentation. Anyway, I will push an updated moose doc file following your suggestions as much as possible. I will add a link to a python inversion code (as Yr 1 deliverable it is just a scalar, effective PDE coefficient calibration tool) uploaded in my github repo but if @rpodgorney is ok with adding the python script to this repo, I will do so. 

I am definitely interested in using MOOSE optimization module and/or INL's UQ code for the project, but I think joint data inversion with geophysics and other (statistical) seismic analysis tools and/or deep learning-based dimension reduction for accelerated UQ eventually need additional works outside the MOOSE toolbox. If this repo is not the right place for the project documentation, I will talk to the PI of the FORGE project and check whether I can use other repos for documentation/reporting. 

Thanks! 
Harry

**Comment by rpodgorney** [comment]
@jonghyunharrylee go ahead and put your python script into the FALCON repo, there is a python directory available

**Comment by rpodgorney** [comment]
Has anything happened recently with the PR?

**Comment by rpodgorney** [comment]
@jonghyunharrylee did you put the python code into the PR?
@loganharbour can you help with logistics to get all tests to pass and ll code checked?
@lynnmunday can you review content and get me some feedback?

**Comment by rpodgorney** [comment]
We can discuss using MOOSE UQ and Inverse capabilities in the future

**Comment by rpodgorney** [comment]
@jonghyunharrylee I'll try to get you a smaller mesh--something that can run quickly

**Comment by lynnmunday** [comment]
@jonghyunharrylee Will you take a look at the changes I made? I had to reduce the alpha in your optimization script because it was taking too big of a step on the permeability.  This is a simplified version of the native state model that uses a coarser mesh so that it will run in a few minutes.  It tests that the python script can run the moose input file.  This passes the tests and builds the documentation.  Before we can merge it, you need to fix all of the numpy deprecation warnings that come up, they have something to do with accesses data in a matrix.

**Comment by rpodgorney** [comment]
@loganharbour does @lynnmunday's change address your change request?

**Comment by lynnmunday** [comment]
@jonghyunharrylee This python deprecation warning from you optimization script needs to be fixed before they merge this code:
``` 
optimization_script.py:296:  DeprecationWarning: Conversion of an array with ndim > 0 to a scalar 
is deprecated, and will error in future.  Ensure you extract a single element from your array before 
performing this operation. (Deprecated NumPy 1.25.)
```

**Comment by jonghyunharrylee** [comment]
Changes look all great. Thanks!

**Comment by lynnmunday** [comment]
@jonghyunharrylee This python deprecation warning from you optimization script needs to be fixed before they merge this code:

optimization_script.py:296:  DeprecationWarning: Conversion of an array with ndim > 0 to a scalar 
is deprecated, and will error in future.  Ensure you extract a single element from your array before 
performing this operation. (Deprecated NumPy 1.25.)

**Comment by lynnmunday** [comment]
@rpodgorney  this is ready to merge.

**Pull request merged**
