### PR TITLE
FALCON website example update

### PR DESCRIPTION
**Pull request by wjin33**
Added one example with a Doc explanation to show as an example on [the FALCON website](https://mooseframework.inl.gov/falcon/examples/index.html)

### CODE REVIEW

**Comment by wjin33** [comment]
Hi, Logan. What else should I do to merge it?

**Comment by loganharbour** [comment]
You still have extra whitespace:

```
##########################################################################
ERROR: The following files do not contain a newline character before EOF:
	include/dirackernels/FunctionEnthalpySink.h
	src/dirackernels/FunctionEnthalpySink.C
	src/dirackernels/PointEnthalpySourceFromFunction.C

Run the "delete_trailing_whitespace.sh" script in your $MOOSE_DIR/scripts directory.
##########################################################################
```

(see https://civet.inl.gov/job/1152940/)

**Comment by rpodgorney** [comment]
@wjin33  @loganharbour I looked through the materials--I'm ok with the content from a technical perspective.  Once the tests go green I'll approve this

**Comment by rpodgorney** [comment]
are you guys making any progress on this?

**Pull request closed without merging**
